before_script:
  - git clone --depth=1 --branch=master https://gitlab.com/xonotic/darkplaces.git darkplaces
  - cd darkplaces && make sv-debug -j $(nproc)
  - cd ..
  - export ENGINE="$PWD/darkplaces/darkplaces-dedicated -xonotic"

  - git clone --depth=1 --branch=master https://gitlab.com/xonotic/gmqcc.git gmqcc
  - cd gmqcc && make -j $(nproc)
  - cd ..
  - export QCC="$PWD/gmqcc/gmqcc"

  - ln -s $PWD data/xonotic-data.pk3dir
  - mkdir maps && wget -O maps/gitlab-ci.bsp https://gitlab.com/xonotic/xonotic-maps.pk3dir/raw/master/maps/_init/_init.bsp

build:
  script:
    - make
    - while read line; do
        echo $line;
        if [[ $line == "All tests OK" ]]; then exit 0; fi;
      done < <(${ENGINE} +developer 1 +map gitlab-ci +sv_cmd runtest +exit)
    - exit 1
  artifacts:
    paths:
      - csprogs.dat

doxygen:  # rename to 'pages' when gitlab.com allows pages to exceed 100MiB
  stage: deploy
  script:
    - cd qcsrc && doxygen
    - mv html ../public
  artifacts:
    paths:
      - public
  only:
    - master
