before_script:
  - git clone --depth=1 --branch=master https://gitlab.com/xonotic/gmqcc.git gmqcc
  - cd gmqcc
  - make -j $(nproc)
  - cd ..
  - export QCC=$PWD/gmqcc/gmqcc

build:
  script:
    - make
